language: rust

os:
  - linux
  - osx

rust:
  - stable
  - beta
  - nightly

script:
  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then
      cargo bench;
      cargo build;
      cargo test;
    else
      cargo build;
      cargo test;
    fi

notifications:
  email: false
